[package]
name = "diy_fortune"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.14"
reqwest = "0.11.11"
tokio = { version = "1.20.0", features = ["full"] }
